const CONST_ZILWATCH_ROOT_URL = 'https://zilwatch.io';
const CONST_STATS_ZILSWAP_ROOT_URL = 'https://stats.zilswap.org';
const CONST_ZILSWAP_REWARD_DISTRIBUTOR_ADDRESS_BASE16 = "0xea57c6b7b5475107688bc70aabefdd5352d0bed0";

// For lightweight charts
const CONST_WHITE_TRANSPARENT_RGBA_STRING = 'rgba(255, 255, 255, 0)';
const CONST_BLACK_TRANSPARENT_RGBA_STRING = 'rgba(0, 0, 0, 0)';
const CONST_GREEN_LINE_RGBA_STRING = 'rgba(83, 165, 81, 1.0)';
const CONST_RED_LINE_RGBA_STRING = 'rgba(203, 68, 74, 1.0)';
const CONST_GREEN_TOP_GRADIENT_RGBA_STRING = 'rgba(83, 255, 81, 1.0)';
const CONST_RED_TOP_GRADIENT_RGBA_STRING = 'rgba(255, 68, 74, 1.0)';

if (typeof exports !== 'undefined') {
    exports.CONST_ZILWATCH_ROOT_URL = CONST_ZILWATCH_ROOT_URL;
    exports.CONST_STATS_ZILSWAP_ROOT_URL = CONST_STATS_ZILSWAP_ROOT_URL;
    exports.CONST_ZILSWAP_REWARD_DISTRIBUTOR_ADDRESS_BASE16 = CONST_ZILSWAP_REWARD_DISTRIBUTOR_ADDRESS_BASE16;

    exports.CONST_WHITE_TRANSPARENT_RGBA_STRING = CONST_WHITE_TRANSPARENT_RGBA_STRING;
    exports.CONST_BLACK_TRANSPARENT_RGBA_STRING = CONST_BLACK_TRANSPARENT_RGBA_STRING;
    exports.CONST_GREEN_LINE_RGBA_STRING = CONST_GREEN_LINE_RGBA_STRING;
    exports.CONST_RED_LINE_RGBA_STRING = CONST_RED_LINE_RGBA_STRING;
    exports.CONST_GREEN_TOP_GRADIENT_RGBA_STRING = CONST_GREEN_TOP_GRADIENT_RGBA_STRING;
    exports.CONST_RED_TOP_GRADIENT_RGBA_STRING = CONST_RED_TOP_GRADIENT_RGBA_STRING;
}
