const CONST_ZILWATCH_ROOT_URL = 'https://zilwatch.io';
const CONST_STATS_ZILSWAP_ROOT_URL = 'https://stats.zilswap.org';
const CONST_ZILSWAP_REWARD_DISTRIBUTOR_ADDRESS_BASE16 = "0xea57c6b7b5475107688bc70aabefdd5352d0bed0";

if (typeof exports !== 'undefined') {
    exports.CONST_ZILWATCH_ROOT_URL = CONST_ZILWATCH_ROOT_URL;
    exports.CONST_STATS_ZILSWAP_ROOT_URL = CONST_STATS_ZILSWAP_ROOT_URL;
    exports.CONST_ZILSWAP_REWARD_DISTRIBUTOR_ADDRESS_BASE16 = CONST_ZILSWAP_REWARD_DISTRIBUTOR_ADDRESS_BASE16;
}
